apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  selector:
    matchLabels:
      app: users
  replicas: 1
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-db/users?createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: rootpss

          image: 'teunkwettercr.azurecr.io/k-users:v1'
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  type: LoadBalancer
  ports:
    - port: 8082
  selector:
    app: users
