version: '3.3'
services:
  message-broker:
    image: rabbitmq:3.8-management
    hostname: message-broker
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  service-tweets:
    image: service-tweets:latest
    hostname: service-tweets
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - message-broker

  service-users:
    image: service-users:latest
    hostname: service-users
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - message-broker