version: '3.3'
services:
  message-broker:
    image: rabbitmq:3.8-management
    hostname: message-broker
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  mysql-db:
    image: mysql:5.6.26
    hostname: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpss
    ports:
      - "3306:3306"
  #   volumes:
  #     - /home/host/docker/mysql-storage/:/var/lib/mysql
  
  # angular-frontend:
  #   build: ./angular-frontend
  #   hostname: angurlar-frontend
  #   ports: 
  #     - "80:80"

  service-tweets:
    build: ./service-tweets
    hostname: service-tweets
    restart: always
    ports:
      - "8081:8081"
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db/tweets?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpss
    depends_on:
      - message-broker
      - mysql-db

  service-users:
    build: ./service-users
    hostname: service-users
    restart: always
    ports:
      - "8082:8082"
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db/users?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpss
    depends_on:
      - message-broker
      - mysql-db

  service-auth:
    build: ./service-auth
    hostname: service-auth
    restart: always
    ports:
      - "8083:8083"
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db/auth?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpss
    depends_on: 
      - mysql-db