pipeline {
    agent {
		node {
			label 'master'
		}
	}
    tools{
        maven 'apache-maven'
        jdk 'JDK 11'
    }
    options {
        skipStagesAfterUnstable()
    }

    stages {
        stage('Docker cleanup'){
            steps{
				sh '''
				docker rmi $(docker images -f 'dangling=true' -q) || true
				docker rmi $(docker images | sed 1,2d | awk '{print $3}') || true
				'''
            }
        }

		// stage('SonarCloud package') {
		// 	steps {
		// 		sh 'mvn -f ./authorization-server/pom.xml verify sonar:sonar'
		// 		sh 'mvn -f ./authorization-server/pom.xml clean package sonar:sonar'
		// 		sh 'mvn -f ./guild/pom.xml verify sonar:sonar'
        //         sh 'mvn -f ./guild/pom.xml clean package sonar:sonar'
		// 	}
		// }

		stage('Docker Build') {
			steps {
				sh 'docker build -t teunkwettercr.azurecr.io/k-auth:kube${BUILD_NUMBER} ./service-auth'
			}
		}

		stage('Docker publish') {
			steps {
				withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId:'acr-credentials', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
				sh 'docker login teunkwettercr.azurecr.io -u $USERNAME -p $PASSWORD'
				sh 'docker push teunkwettercr.azurecr.io/k-auth:kube${BUILD_NUMBER}'
				sh 'docker logout'
				}
			}
		}
		stage('kubetcl set') {
        			steps {
        				sh 'kubectl set image deployment/auth auth=teunkwettercr.azurecr.io/k-auth:kube${BUILD_NUMBER} --kubeconfig /home/jenkins/.kube/config'
        			}
        		}
    }
}